Repository PJ-Plan-Journey/PJ-Plan-Journey-BE, pull requests merged in 2024-08, with the labels that each got.

#21 Feature/save plan 8
  src/main/java/com/pj/planjourney/domain/city/repository/CityRepository.java
  src/main/java/com/pj/planjourney/domain/plan/contoller/PlanController.java
  src/main/java/com/pj/planjourney/domain/plan/dto/CreatePlanRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/CreatePlanResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
  src/main/java/com/pj/planjourney/domain/plan/repository/PlanRepository.java
  src/main/java/com/pj/planjourney/domain/plan/service/PlanService.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/CreatePlanDetailRequestDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/CreatePlanDetailResponseDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/PlanDetail.java
  src/main/java/com/pj/planjourney/domain/plandetail/repository/PlanDetailRepository.java
  src/main/java/com/pj/planjourney/domain/user/entity/User.java
  src/main/java/com/pj/planjourney/domain/user/entity/repository/UserRepository.java
  src/main/java/com/pj/planjourney/domain/userPlan/entity/InvitedStatus.java
  src/main/java/com/pj/planjourney/domain/userPlan/entity/UserPlan.java
  src/main/java/com/pj/planjourney/domain/userPlan/repository/UserPlanRepository.java
  src/main/java/com/pj/planjourney/global/common/exception/ExceptionCode.java
  src/main/java/com/pj/planjourney/global/common/response/ApiResponseMessage.java
Labels: feature

#28 Feature/edit plan 6
  build.gradle
  src/main/java/com/pj/planjourney/domain/city/entity/City.java
  src/main/java/com/pj/planjourney/domain/plandetail/config/RedisConfig.java
  src/main/java/com/pj/planjourney/domain/plandetail/config/WebSocketConfig.java
  src/main/java/com/pj/planjourney/domain/plandetail/controller/EditPlanDetailController.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/EditPlanDetailRequestDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/EditPlanDetailResponseDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/PlanDetailDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/EditPlanType.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/PlanDetail.java
  src/main/java/com/pj/planjourney/domain/plandetail/repository/PlanDetailRepository.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/EditPlanDetailService.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/RedisPublisher.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/RedisSubscriberPlanUpdates.java
Labels: feature

#32 Fix/redis 31
  src/main/java/com/pj/planjourney/domain/plandetail/config/RedisPubSubConfig.java
  src/main/java/com/pj/planjourney/domain/plandetail/controller/EditPlanDetailController.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/EditPlanDetailResponseDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/EditPlanDetailService.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/RedisPublisher.java
  src/main/java/com/pj/planjourney/global/config/SecurityConfig.java
Labels: bug

#33 Feature/plan 10
  build.gradle
  src/main/java/com/pj/planjourney/domain/childcomment/controller/ChildCommentController.java
  src/main/java/com/pj/planjourney/domain/childcomment/dto/ChildCommentCreateRequestDto.java
  src/main/java/com/pj/planjourney/domain/childcomment/dto/ChildCommentCreateResponseDto.java
  src/main/java/com/pj/planjourney/domain/childcomment/dto/ChildCommentListResponseDto.java
  src/main/java/com/pj/planjourney/domain/childcomment/dto/ChildCommentUpdateRequestDto.java
  src/main/java/com/pj/planjourney/domain/childcomment/dto/ChildCommentUpdateResponseDto.java
  src/main/java/com/pj/planjourney/domain/childcomment/entity/ChildComment.java
  src/main/java/com/pj/planjourney/domain/childcomment/repository/ChildCommentRepository.java
  src/main/java/com/pj/planjourney/domain/childcomment/service/ChildCommentService.java
  src/main/java/com/pj/planjourney/domain/comment/controller/CommentController.java
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentCreateRequestDto.java
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentCreateResponseDto.java
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentListResponseDto.java
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentUpdateResponseDto.java
  src/main/java/com/pj/planjourney/domain/comment/entity/Comment.java
  src/main/java/com/pj/planjourney/domain/comment/repository/CommentRepository.java
  src/main/java/com/pj/planjourney/domain/comment/service/CommentService.java
  src/main/java/com/pj/planjourney/domain/like/controller/LikeController.java
  src/main/java/com/pj/planjourney/domain/like/dto/LikeCountResponseDto.java
  src/main/java/com/pj/planjourney/domain/like/entity/Like.java
  src/main/java/com/pj/planjourney/domain/like/repository/LikeRepository.java
  src/main/java/com/pj/planjourney/domain/like/service/LikeService.java
  src/main/java/com/pj/planjourney/domain/plan/controller/PlanController.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanCopyResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanCreateRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanCreateResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanInfoRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanInfoResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanListRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanListResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanUpdateTitleRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanUpdateTitleResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
  src/main/java/com/pj/planjourney/domain/plan/repository/PlanRepository.java
  src/main/java/com/pj/planjourney/domain/plan/service/PlanService.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/PlanDetail.java
Labels: feature

#41 Feature/invite 38
  src/main/java/com/pj/planjourney/domain/plan/service/PlanService.java
  src/main/java/com/pj/planjourney/domain/userPlan/controller/UserPlanController.java
  src/main/java/com/pj/planjourney/domain/userPlan/dto/AcceptInvitePlanRequestDto.java
  src/main/java/com/pj/planjourney/domain/userPlan/dto/InviteFriendsRequestDto.java
  src/main/java/com/pj/planjourney/domain/userPlan/dto/InvitedPlanResponseDto.java
  src/main/java/com/pj/planjourney/domain/userPlan/entity/InvitedStatus.java
  src/main/java/com/pj/planjourney/domain/userPlan/entity/UserPlan.java
  src/main/java/com/pj/planjourney/domain/userPlan/repository/UserPlanRepository.java
  src/main/java/com/pj/planjourney/domain/userPlan/service/UserPlanService.java
  src/main/java/com/pj/planjourney/global/common/exception/ExceptionCode.java
Labels: feature

#48 Feature/save plan 46
  src/main/java/com/pj/planjourney/domain/plan/controller/PlanController.java
  src/main/java/com/pj/planjourney/domain/plan/dto/CreatePlanRequestDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/CreatePlanResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
  src/main/java/com/pj/planjourney/global/auth/service/UserDetailsImpl.java
Labels: feature

#52 Feature/notification 25
  src/main/java/com/pj/planjourney/domain/friend/controller/FriendController.java
  src/main/java/com/pj/planjourney/domain/friend/dto/FriendRequestSendResponseDto.java
  src/main/java/com/pj/planjourney/domain/friend/service/FriendService.java
  src/main/java/com/pj/planjourney/domain/notification/controller/NotificationController.java
  src/main/java/com/pj/planjourney/domain/notification/dto/NotificationMessage.java
  src/main/java/com/pj/planjourney/domain/notification/service/NotificationService.java
  src/main/java/com/pj/planjourney/global/config/WebSocketConfig.java
Labels: bug

#53 Feature/notification 25
  src/main/java/com/pj/planjourney/domain/friend/controller/FriendController.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanInfoResponseDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/PlanDetail.java
Labels: bug

#55 feature : 친구요청목록조회 응답값으로 friendRequestId 추가
  src/main/java/com/pj/planjourney/domain/friend/dto/FriendRequestResponseDto.java
  src/main/java/com/pj/planjourney/domain/friend/service/FriendService.java
Labels: feature

#58 fix : 친구 수락시 친구요청테이블에 저장된 해당 레코드 삭제되게 수정
  src/main/java/com/pj/planjourney/domain/friend/service/FriendService.java
Labels: bug

#59 fix : 친구 거절시 친구요청테이블에 저장된 해당 레코드 삭제되게 수정
  src/main/java/com/pj/planjourney/domain/friend/service/FriendService.java
Labels: bug

#60 fix : createComment Service 파라미터값 수정
  src/main/java/com/pj/planjourney/domain/comment/service/CommentService.java
Labels: bug

#61 fix : friend 삭제 입력값 경로변수로 변경
  src/main/java/com/pj/planjourney/domain/comment/dto/CommentCreateResponseDto.java
  src/main/java/com/pj/planjourney/domain/friend/controller/FriendController.java
  src/main/java/com/pj/planjourney/domain/friend/service/FriendService.java
Labels: bug

#62 fix : friend 삭제 입력값 경로변수 수정
  src/main/java/com/pj/planjourney/domain/friend/controller/FriendController.java
Labels: bug

#63 fix : friend 목록조회시 응답값으로 nickname추가
  src/main/java/com/pj/planjourney/domain/friend/dto/FriendResponseDto.java
Labels: bug

#64 fix : FriendRequestResponseDto에 응답값으로 senderNickname,receiverNickname 추가
  src/main/java/com/pj/planjourney/domain/friend/dto/FriendRequestResponseDto.java
Labels: bug

#65 rename : getAllChildComment 파라미터 변수 이름 변경
  src/main/java/com/pj/planjourney/domain/childcomment/controller/ChildCommentController.java
  src/main/java/com/pj/planjourney/domain/childcomment/service/ChildCommentService.java
Labels: bug

#68 feature : sse를 사용한 실기간 알림 기능
  src/main/java/com/pj/planjourney/domain/notification/service/NotificationService.java
  src/main/java/com/pj/planjourney/domain/sse/controller/EventController.java
  src/main/java/com/pj/planjourney/domain/sse/service/EventService.java
  src/main/java/com/pj/planjourney/domain/userPlan/service/UserPlanService.java
  src/main/java/com/pj/planjourney/global/config/RedisConfig.java
Labels: feature

#69 Feature/edit 67
  src/main/java/com/pj/planjourney/domain/plandetail/controller/EditPlanDetailController.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/EditPlanDetailRequestDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/EditPlanDetailResponseDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/dto/InsertRequestDto.java
  src/main/java/com/pj/planjourney/domain/plandetail/entity/PlanDetail.java
  src/main/java/com/pj/planjourney/domain/plandetail/service/EditPlanDetailService.java
Labels: feature

#72 Feature/plan
  src/main/java/com/pj/planjourney/domain/plan/dto/CreatePlanResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanInfoResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanListResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
  src/main/java/com/pj/planjourney/domain/plan/service/PlanService.java
Labels: feature

#73 fix : cascade 설정 수정
  src/main/java/com/pj/planjourney/domain/comment/entity/Comment.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
Labels: bug

#74 fix : getPlan 할 때 sequence 순서대로 정렬하는 기능 추가
  src/main/java/com/pj/planjourney/domain/plan/service/PlanService.java
  src/main/java/com/pj/planjourney/domain/plandetail/repository/PlanDetailRepository.java
Labels: bug

#76 feature : 내일정으로 가져오기 요청시 응답으로 작성자, 시작일, 끝나는일 추가
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
Labels: bug, feature

#77 feature : getPlan 요청시 commentCount 응답값 추가
  src/main/java/com/pj/planjourney/domain/plan/dto/PlanListResponseDto.java
  src/main/java/com/pj/planjourney/domain/plan/entity/Plan.java
Labels: bug
